export interface ICoin {
    "positionId": number,
    "productId": string,
    "asset": string,
    "amount": string,
    "purchaseTime": number,
    "duration": number,
    "accrualDays": number,
    "rewardAsset": string,
    "rewardAmt": string,
    "nextInterestPay": string,
    "nextInterestPayDate": number,
    "payInterestPeriod": number,
    "redeemAmountEarly": string,
    "interestEndDate": number,
    "deliverDate": number,
    "redeemPeriod": number,
    "canRedeemEarly": boolean,
    "renewable": boolean,
    "type": string,
    "status": string,
    "canReStake": boolean,
    "apy": string
}